### ISSUE TITLE
Unable to replicate CO Case Study

### ISSUE THREAD

**Issue by scharf-roie** [peterhcharlton/pwdb#2]
I am currently trying to replicate the Cardiac Output case study using MatLab R2020a via Citrix Workspace on a Windows 10 OS. I currently have PATHS.storage_folder = 'C:/Desktop/'; and have followed the current directions provided in GitHub. I was wondering if a member of the original team would be able to help me with this issue and get the code to run successfully. 

Thanks

![caseStudyTroubleshoot](https://user-images.githubusercontent.com/85931004/123920710-eb3a9300-d98e-11eb-99ce-5a521d6a9cb1.JPG)

**Comment by Qhan-Hu** [comment]
Hello, sorry to bother you. When running the script "extract_pwdb_simulation_data.m", I encountered an error that the variable "output_folder" (line156) cannot be recognized. I noticed that it does not seem to be defined in the script. Have you encountered a similar situation?
